### ISSUE TITLE
NX Cloud Bot not working

### ISSUE THREAD

**Issue by cyrus-za** [MansaGroup/nrwl-nx-action#12]
At the off-chance that the issue is related to this GH action, I am linking it.

https://github.com/nrwl/nx/issues/4534

**Comment by IamBlueSlime** [comment]
Hi!

I never used Nx Cloud so I'm afraid that I won't be of much help for you on this. Is your pipeline running correctly on Nx Cloud? If yes, maybe it's a bug on Nx's side if the comment isn't posted of the PR. Otherwise if the pipeline is not triggered at all maybe there is a bug in this action.

But to be honest, the action is just spawning the Nx command... I don't really know what and where to search :/

**Comment by IamBlueSlime** [comment]
I've found this article from Nx themselves: https://blog.nrwl.io/introducing-run-details-available-now-on-nx-cloud-d2da86361862

> --scan argument each time, but if you’re sure you want to do this for every run, you can add "scan" : true to the tasksRunnerOptions in nx.json at the root of the repository.

I'm not setting the `--scan` option, could you test by setting it directly in your `nx.json` file?

**Comment by cyrus-za** [comment]
I already have scan set to true on nx.json, but that wont affect the bot afaik, it just doesn't add command logs to cloud output (only run results). 

Nx cloud has been working from the start (over a month). The bot just does not post to the PR which makes me think the env I added to the action is not reachig nx cloud to say which PR is being run.

**Comment by IamBlueSlime** [comment]
I will add some inputs to the action to accept some Nx Cloud-only options like the auth token to simplify the usage. Then I will public a pre-release and will ping you back to test on this pre-release :)

**Comment by IamBlueSlime** [comment]
Hi @cyrus-za!

Sorry for the long time! I've published a pre-release named `v2.1.0`. It's adds the support of Nx Cloud with the new `nxCloud` input. If you set it to `'true'` it should fix your issue. Could you test on your side and give me some feedbacks?

Thanks!

**Comment by cyrus-za** [comment]
I updated and enabled it. Did not work
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/1845861/108059311-fdf6a000-705d-11eb-9f68-e1c3e031aa9c.png">

**Comment by cyrus-za** [comment]
Closing this. I had a call with nx support. Reason the bot doesn't show up is because I am using a github secret for the nx cloud auth token, which is not currently supported. They require the token committed to source control inside nx.json in order to detect which repo these actions are running from.
