### ISSUE TITLE
Does not identify git boundaries correctly with rebase merge or push directly to branch 

### ISSUE THREAD

**Issue by JoA-MoS** [MansaGroup/nrwl-nx-action#120]
## Bug Report

I believe the git boundaries are not being defined correctly when not using a merge or squash commit to a branch that runs your workflow.

## Current behavior

If you choose rebase merge in your PR to add directly onto the target branch even if that PR contained 10 commits the base ref would be set to HEAD~1. I believe the same would happen if you pushed multiple commits directly to master/main without using a PR.

## Expected behavior

When pushing to master the base ref should be reported as the target HEAD before the PR was merged. 

## Possible Solution

1. use github.events to get the values - https://stackoverflow.com/a/61861763/2770668
2. allow configuration to send baseRef and override the git boundaries logic
3. Call out in the documentation this limitation, until fixed.

**Comment by IamBlueSlime** [comment]
That's pretty interesting. Didn't know about the `before` in push-based events. Will look into it ASAP.
Thanks!

**Comment by IamBlueSlime** [comment]
Re, @JoA-MoS. I've published a v2.0.6 pre-release. Could you please try it out on your workflows and tell me if everything is good for you?

```yaml
- uses: mansagroup/nrwl-nx-action@v2.0.6
```

Thanks!

**Comment by JoA-MoS** [comment]
Thank you! I tested it out and it looks good here is the github job action where it ran https://github.com/semantic-release-plus/semantic-release-plus/actions/runs/1212277629 if you want to see the output.

**Comment by IamBlueSlime** [comment]
That's cool! Thanks for your help, I've published the new release!
