### ISSUE TITLE
clarification: running e2e tests within the action

### ISSUE THREAD

**Issue by pulanski** [MansaGroup/nrwl-nx-action#236]
This isn't really a feature request, rather me trying to get some clarification. I was reviewing your action here https://github.com/marketplace/actions/nrwl-nx. I see that you guys have mentioned that build, test, lint, and deploy are all included. I was wondering if I could also run e2e tests on affected projects with this action out of the box, or if I would need to configure that myself.

**Comment by IamBlueSlime** [comment]
Hi @pulanski, sorry for the time, I was quite busy working on my company's projects.

Thank you for opening the issue. The tasks I've listed on the documentation are just examples. It can execute any task of any project, even if the task is present only on one project and not the others. There is no restriction on whatever :)
