### ISSUE TITLE
Failed to locate the 'nx' script in package.json

### ISSUE THREAD

**Issue by well-balanced** [MansaGroup/nrwl-nx-action#280]
## Bug Report

I've faced the error **`Failed to locate the 'nx' script in package.json`** so I found the function `assertHasNxPackageScript` in this code base. this function checks `package.json` for nx commands. but I don't have the "nx" command even I started a project with `nx-cli`.

```ts
async function assertHasNxPackageScript(): Promise<void> {
  const packageJson = await loadPackageJson().catch(() => {
    throw new Error(
      "Failed to load the 'package.json' file, did you setup your project correctly?",
    );
  });

  core.info('Found package.json file');

  if (typeof packageJson.scripts?.nx !== 'string') // this line
    throw new Error(
      "Failed to locate the 'nx' script in package.json, did you setup your project with Nx's CLI?",
    );

  core.info("Found 'nx' script inside package.json file");
}
```

I actually don't know if this function has a bug. but if you know any solution please guide me. thx :)

**P.S. I'm using [act](https://github.com/nektos/act) for the test locally**

**Comment by IamBlueSlime** [comment]
Hi!

Previous Nx generated workspaces contained an `nx` script in the `package.json`'s scripts section. You can add it yourself:

```json
{
  ...
  "scripts": {
    "nx": "nx"
  }
}
```

Do not hesitate to re-open the issue is something goes wrong :)
