### ISSUE TITLE
Disabling parallel does not result in correct CLI arguments, and actually runs in parallel

### ISSUE THREAD

**Issue by samuelfernandez** [MansaGroup/nrwl-nx-action#299]
## Current behavior

When passing `parallel: 'false'` it does not pass the param. Since the default is `--parallel=3`, it will result in parallelization

## Expected behavior

Passing `parallel: 'false'` doesn't result in parallelization

## Possible Solution

Convert it into `--parallel=1`

---

**Others:**

**Comment by samuelfernandez** [comment]
Workaround by now: https://github.com/nx-squeezer/squeezer/commit/ff9f455f65bc68e42417675855c2442e0a630420

**Comment by IamBlueSlime** [comment]
Hi @samuelfernandez. Nx changed their parameters and renamed `maxParallel` to `parallel` directly, which caused issue with this action. It is now fixed and released under `v3`.

Thanks!
