### ISSUE TITLE
Error: '/usr/bin/git' ambiguous argument 'HEAD~1'

### ISSUE THREAD

**Issue by scorsi** [MansaGroup/nrwl-nx-action#31]
## Bug Report

I'm running into a bug with version `2.1.0` and `2.0.3` 

OS: `Ubuntu  18.04.5  LTS`

## Current behavior

```
Run mansagroup/nrwl-nx-action@v2.1.0
  with:
    nxCloud: true
    targets: lint,test,build,deploy
    all: false
    affected: true
    parallel: false
    maxParallel: 3
  env:
    NX_BRANCH: 
    NX_HEAD: 
    NX_RUN_GROUP: 614141274
    TAG: 9f79beb6b5d95548db67ef9b1c63e1cc8e16c19c
🔍 Ensuring Nx is available
  Found package.json file
  Found 'nx' script inside package.json file
  Using npm as package manager
🏷 Retrieving Git boundaries (affected command)
  /usr/bin/git rev-parse HEAD~1
  fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  HEAD~1
Error: Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by IamBlueSlime** [comment]
Hi! That's because you are not cloning your repository with enough depth to deduce the affected projects. I will add a disclaimer in the README to avoid any confusion in the future.

To fix this, a possibility is to add a `fetch-depth: 0` entry to your `actions/checkout` step:
```yaml
- uses: actions/checkout@v2
   with:
   fetch-depth: 0
```

**Comment by scorsi** [comment]
Sorry for the delay @IamBlueSlime, just missing the `fetch-depth: 0` exact !

**Comment by bbugh** [comment]
FYI `fetch-depth: 2` works and will result in a smaller and faster download.

**Comment by scorsi** [comment]
@bbugh just depends, I have some project in my NX project not updated since +50 commits :)
