### ISSUE TITLE
The "projects" paramater is ignored and nx runs all projects

### ISSUE THREAD

**Issue by MayaHanna** [MansaGroup/nrwl-nx-action#325]
## Current behavior

Hello!
I'm trying to run the action with "projects" parameters, and instead of running only the project I defined,  the action runs all the projects.

<br class="Apple-interchange-newline">

main.yml:

`- name: Nrwl Nx
        uses: MansaGroup/nrwl-nx-action@v3.2.1
        with:
          targets: e2e
          args: --verbose  --mainArgs="--port=5000"
          affected: false
          projects: solar-dashboard-e2e
          all: false`

The result:

`/usr/local/bin/npx nx run-many --target=e2e --all --verbose --mainArgs=--port=5000 --parallel=3
>  NX  Running target e2e for 4 project(s):
  - solar-dashboard-e2e
  - solar-dashboard
  - image-analysis
  - main
  
  With flags:
    --verbose=true
    --mainArgs=--port=5000`

I tried it also without "all"- same results.

**Comment by IamBlueSlime** [comment]
Hi @MayaHanna 

I confirm the bug you have, by looking through the code I see that explicitly setting `affected` to `false` make the code falls into the first if condition here:

https://github.com/MansaGroup/nrwl-nx-action/blob/main/src/run-nx.ts#L119-L121

I will refactor this a bit to take into account the `projects` field first, which should solve the issue.

**Comment by IamBlueSlime** [comment]
I've released a new `v3.2.2` version, but you can use `v3` directly. Tell me if your issue is fixed :)
