### ISSUE TITLE
Ability to pass configuration options to targets

### ISSUE THREAD

**Issue by AgentEnder** [MansaGroup/nrwl-nx-action#37]
## Is your feature request related to a problem? Please describe.

For builds you may want to build targeting production within your CI or other environments.

## Describe the solution you'd like

Add an input for flags passed to the commands. The main drawback here is that the flags would be the same for each target passed, and it may require splitting the targets out into different steps of the GHA workflow.

**Comment by IamBlueSlime** [comment]
Hi!

This feature is already available through a `args` input which, indeed, will append the same input to all targets, [see here](https://github.com/MansaGroup/nrwl-nx-action#inputs).

I don't think adding a complexity layer is relevant, I advise you to split into different steps if you need to pass different args.

**Comment by AgentEnder** [comment]
Wow, my bad. I looked over the docs and missed that one somehow. I'll close this :).
