### ISSUE TITLE
pnpm not working

### ISSUE THREAD

**Issue by cyrus-za** [MansaGroup/nrwl-nx-action#4]
nx officially supports pnpm, but this github action fails. 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1845861/103415041-251a1080-4b89-11eb-8de8-ab8aef9caeb5.png">

**Comment by cyrus-za** [comment]
PR here https://github.com/MansaGroup/nrwl-nx-action/pull/5

**Comment by cyrus-za** [comment]
Thanks for the fast response. Keep up the good work

**Comment by cyrus-za** [comment]
Sorry to be a pain, but I opened another PR. pnpm, just like npm, needs the `--` in front of args

**Comment by IamBlueSlime** [comment]
No worry, it happens 👍 
I guess you can use your fork directly in your Actions workflows to test if your patches works. Just replace the repository owner & name in the `use:` statement.
