### ISSUE TITLE
Not a valid commit name

### ISSUE THREAD

**Issue by OmarioHasan** [MansaGroup/nrwl-nx-action#75]
## Current behavior
I'm trying to detect affected projects between 2 branches **"dev,tst"**

![image](https://user-images.githubusercontent.com/8146344/122668649-5fb84980-d1b9-11eb-8a71-87dab2a7c124.png)

I got an error message **Not a valid commit name**

![image](https://user-images.githubusercontent.com/8146344/122668656-68a91b00-d1b9-11eb-9141-336c9e4c462a.png)

and It's working locally well

![image](https://user-images.githubusercontent.com/8146344/122668668-7b235480-d1b9-11eb-9461-7e1d640177a9.png)

I'm not sure what is wrong I've made

**Comment by IamBlueSlime** [comment]
Hi!
You don’t have enough Git history. You'll have to tune your Checkout actions to pull more than the last commits using the `fetch-depth` option.
I use `fetch-depth: 0` in my repositories to pull the whole history ; but 2 should be sufficient.

**Comment by OmarioHasan** [comment]
Sorry I didn't understand 
What exactly I need to do to fix
